version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: dinesh
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  pgbouncer:
    image: edoburu/pgbouncer
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt
    command: [ "pgbouncer", "/etc/pgbouncer/pgbouncer.ini" ]



  web:
    build: .
    command: ./bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - pgbouncer
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://dinesh:password@pgbouncer:6432/oms_development
      REDIS_URL: redis://redis:6379/1

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/rails
    depends_on:
      - db
      - redis
      - pgbouncer
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://dinesh:password@pgbouncer:6432/oms_development
      REDIS_URL: redis://redis:6379/1

volumes:
  pgdata:
