version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: dinesh
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  pgbouncer:
    image: edoburu/pgbouncer
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt
    command: [ "pgbouncer", "/etc/pgbouncer/pgbouncer.ini" ]

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      ALLOW_PLAINTEXT_LISTENER: yes

  web:
    build: .
    command: ./bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - pgbouncer
      - kafka
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://dinesh:password@pgbouncer:6432/oms_development
      REDIS_URL: redis://redis:6379/1
      KAFKA_BROKER: kafka:9092

  karafka:
    build: .
    command: bundle exec karafka server
    volumes:
      - .:/rails
    depends_on:
      - kafka
      - db
      - pgbouncer
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://dinesh:password@pgbouncer:6432/oms_development
      REDIS_URL: redis://redis:6379/1
      KAFKA_BROKER: kafka:9092

volumes:
  pgdata:
