version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: dinesh
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  pgbouncer:
    image: edoburu/pgbouncer
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt
    command: [ "pgbouncer", "/etc/pgbouncer/pgbouncer.ini" ]

  kafka:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    ports:
      - "9092:9092"
    command: >
      redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M
      --node-id 0 --check=false

  web:
    build: .
    command: ./bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - pgbouncer
      - kafka
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://dinesh:password@pgbouncer:6432/oms_development
      REDIS_URL: redis://redis:6379/1
      KAFKA_BROKER: kafka:9092

  karafka:
    build: .
    command: bundle exec karafka server
    volumes:
      - .:/rails
    depends_on:
      - kafka
      - db
      - pgbouncer
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://dinesh:password@pgbouncer:6432/oms_development
      REDIS_URL: redis://redis:6379/1
      KAFKA_BROKER: kafka:9092

volumes:
  pgdata:
